### ISSUE TITLE
Add alerts for 0/1 containers

### ISSUE THREAD

**Issue by kumarnarendra701** [atsign-company/shepherd#6]
**Describe the bug**
Add checks for 1/0 containers in a daily check.

**Comment by athandle** [comment]
linked to https://github.com/atsign-foundation/at_server/issues/622

**Comment by kumarnarendra701** [comment]
@cconstab - Created a similar behavior by deleting directory on test secondary and I can see that seccheck job sending alerts to for problematic secondary on gchat channel.

```
root@staging0001-01:~# docker service ls | grep 58d7ae57-08bb-5053-868b-91794734fedd
67roiarn658n   58d7ae57-08bb-5053-868b-91794734fedd_secondary   replicated   0/1        reg.staging0001.atsign.zone/atsigncompany/secondary:dev_env      *:12490->12490/tcp
```
Alerts - Of the 1 these are the first few effected @signs,  @test_ashish7 (12490),

**Comment by athandle** [comment]
@cconstab  can you please confirm

**Comment by athandle** [comment]
closing this ticket and continue using https://github.com/atsign-foundation/at_server/issues/622
